# Rock Creek Ranch Pastures

# Herbaceous model uses the NDTI (SWIR1-SWIR2/SWIR1+SWIR2) for
# both summer and fall

# Shrub model for now uses very different indices, the enhanced
# vegetation index (EVI) which might be a product and the
# tasseled cap greeness index

# multiple models can be defined. e.g. Herbaceous and Shrub
# 2.23651048, 11.81505156,  4.12366473,  2.84975185,  0.03850698])
models:
    - name: Herbaceous
      satellite_pars:
          - satellite: 8
            discriminate_threshold: 0.03850698
            discriminate_index: psri
            summer_int: 4.12366473
            summer_slp: 2.84975185
            summer_index: nbr
            fall_int: 2.23651048
            fall_slp: 11.81505156
            fall_index: nbr2
            required_coverage: 0.5
            minimum_area_ha: 1.8
            log_transformed_estimate: True
          - satellite: 7
            discriminate_threshold: 0.03850698
            discriminate_index: psri
            summer_int: 4.12366473
            summer_slp: 2.84975185
            summer_index: nbr
            fall_int: 2.23651048
            fall_slp: 11.81505156
            fall_index: nbr2
            required_coverage: 0.5
            minimum_area_ha: 1.8
            log_transformed_estimate: True
          - satellite: 5
            discriminate_threshold: 0.03850698
            discriminate_index: psri
            summer_int: 4.12366473
            summer_slp: 2.84975185
            summer_index: nbr
            fall_int: 2.23651048
            fall_slp: 11.81505156
            fall_index: nbr2
            required_coverage: 0.5
            minimum_area_ha: 1.8
            log_transformed_estimate: True

# shapefile containing pastures to analyze
sf_fn: /geodata/torch-landsat/rangesat/SageSteppe/vector_data/RockCreekRanch_habitatmodeled.shp

# primary key for pastures in shapefile
# e.g. key = feature['properties'][sf_feature_properties_key]
sf_feature_properties_key: PastID_Key

# location to place cropped landsat scenes and biomass rasters
out_dir: /geodata/torch-landsat/rangesat/SageSteppe/analyzed_rasters

# directory containing extracted landsat scenes
landsat_scene_directory: /geodata/torch-landsat

wrs_whitelist: []

# path rows that should be skipped
wrs_blacklist: []
