# Rock Creek Ranch Pastures

# Herbaceous model uses the NDTI (SWIR1-SWIR2/SWIR1+SWIR2) for
# both summer and fall

# Shrub model for now uses very different indices, the enhanced
# vegetation index (EVI) which might be a product and the
# tasseled cap greeness index

# multiple models can be defined. e.g. Herbaceous and Shrub
models:
    - name: Herbaceous
      satellite_pars:
          - satellite: 8
            ndvi_threshold: 0.31
            summer_int: -133.2
            summer_slp: 1401.2
            fall_int: -157.0
            fall_slp: 1364.4
            required_coverage: 0.5
            minimum_area_ha: 1.8
          - satellite: 7
            ndvi_threshold: 0.31
            summer_int: -133.2
            summer_slp: 1401.2
            fall_int: -157.0
            fall_slp: 1364.4
            required_coverage: 0.5
            minimum_area_ha: 1.8
          - satellite: 5
            ndvi_threshold: 0.31
            summer_int: -133.2
            summer_slp: 1401.2
            fall_int: -157.0
            fall_slp: 1364.4
            required_coverage: 0.5
            minimum_area_ha: 1.8
    - name: Shrub
      satellite_pars:
          - satellite: 8
            ndvi_threshold: 0.38
            summer_int: 101.09
            summer_slp: 330.25
            fall_int: -58.04
            fall_slp: 1070.64
            required_coverage: 0.5
            minimum_area_ha: 1.8
          - satellite: 7
            ndvi_threshold: 0.32
            summer_int: 104.06
            summer_slp: 343.18
            fall_int: -56.45
            fall_slp: 1042.00
            required_coverage: 0.5
            minimum_area_ha: 1.8
          - satellite: 5
            ndvi_threshold: 0.32
            summer_int: 104.06
            summer_slp: 343.18
            fall_int: -56.45
            fall_slp: 1042.00
            required_coverage: 0.5
            minimum_area_ha: 1.8

# shapefile containing pastures to analyze
sf_fn: /geodata/rangesat/RCR/vector_data/RockCreekRanch_habitatmodeled.shp

# primary key for pastures in shapefile
# e.g. key = feature['properties'][sf_feature_properties_key]
sf_feature_properties_key: PastID_Key

sf_feature_properties_delimiter: -

# location to place cropped landsat scenes and biomass rasters
out_dir: /geodata/rangesat/RCR/analyzed_rasters

# directory containing extracted landsat scenes
landsat_scene_directory: /geodata/torch-landsat

wrs_whitelist: []

# path rows that should be skipped
wrs_blacklist: [042029]
