# Rock Creek Ranch Pastures

# Herbaceous model uses the NDTI (SWIR1-SWIR2/SWIR1+SWIR2) for
# both summer and fall

# Shrub model for now uses very different indices, the enhanced
# vegetation index (EVI) which might be a product and the
# tasseled cap greeness index

# multiple models can be defined. e.g. Herbaceous and Shrub
models:
    - name: Herbaceous
      satellite_pars:
          - satellite: 8
            ndvi_threshold: 0.31
            summer_int: -133.2
            summer_slp: 1401.2
            summer_index: ndti
            fall_int: -157.0
            fall_slp: 1364.4
            fall_index: ndti
            required_coverage: 0.5
            minimum_area_ha: 1.8
          - satellite: 7
            ndvi_threshold: 0.31
            summer_int: -133.2
            summer_slp: 1401.2
            summer_index: ndti
            fall_int: -157.0
            fall_slp: 1364.4
            fall_index: ndti
            required_coverage: 0.5
            minimum_area_ha: 1.8
          - satellite: 5
            ndvi_threshold: 0.31
            summer_int: -133.2
            summer_slp: 1401.2
            summer_index: ndti
            fall_int: -157.0
            fall_slp: 1364.4
            fall_index: ndti
            required_coverage: 0.5
            minimum_area_ha: 1.8

# shapefile containing pastures to analyze
sf_fn: /geodata/torch-landsat/rangesat/RCR/vector_data/RockCreekRanch_habitatmodeled.shp

# primary key for pastures in shapefile
# e.g. key = feature['properties'][sf_feature_properties_key]
sf_feature_properties_key: PastID_Key

# location to place cropped landsat scenes and biomass rasters
out_dir: /geodata/torch-landsat/rangesat/RCR/analyzed_rasters

# directory containing extracted landsat scenes
landsat_scene_directory: /geodata/torch-landsat

#wrs_whitelist: None

# path rows that should be skipped
#wrs_blacklist: None
