# Zumwalt Prairie Pastures

# multiple models can be defined. e.g. Herbaceous and Shrub
models:
    - name: Herbaceous
      satellite_pars:
          - satellite: 8
            discriminate_threshold: 0.38
            discriminate_index: ndvi
            summer_int: 101.09
            summer_slp: 330.25
            summer_index: nbr
            fall_int: -58.04
            fall_slp: 1070.64
            fall_index: nbr2
            required_coverage: 0.5
            minimum_area_ha: 1.8
            log_transformed_estimate: False
          - satellite: 7
            discriminate_threshold: 0.32
            discriminate_index: ndvi
            summer_int: 104.06
            summer_slp: 343.18
            summer_index: nbr
            fall_int: -56.45
            fall_slp: 1042.00
            fall_index: nbr2
            required_coverage: 0.5
            minimum_area_ha: 1.8
            log_transformed_estimate: False
          - satellite: 5
            discriminate_threshold: 0.32
            discriminate_index: ndvi
            summer_int: 104.06
            summer_slp: 343.18
            summer_index: nbr
            fall_int: -56.45
            fall_slp: 1042.00
            fall_index: nbr2
            required_coverage: 0.5
            minimum_area_ha: 1.8
            log_transformed_estimate: False

# shapefile containing pastures to analyze
sf_fn: /space/rangesat/Zumwalt/vector_data/Pastures_ForageAreas_2018_AllZumClip.shp

# primary key for pastures in shapefile
# e.g. key = feature['properties'][sf_feature_properties_key]
sf_feature_properties_key: PastID_Key

# location to place cropped landsat scenes and biomass rasters
out_dir: /space/rangesat/Zumwalt/analyzed_rasters

# directory containing extracted landsat scenes
landsat_scene_directory: /geodata/torch-landsat

# path rows that should be skipped
wrs_blacklist: []

wrs_whitelist: [042028, 043028, 042029]